server:
  port: 9002
spring:
  main:
    allow-circular-references: true
  cloud:
    gateway:
      routes:
        - id: card-service-route # 路由的id,要保证其唯一性
          uri: lb://card-service # lb 表示 从nacos 中按照名称获取微服务，并遵循负载均衡策略, card-service 即微服务注册名
          predicates:
            - Path=/cards/**  # 使用断言
          filters:
        - id: user-service-route # 路由的id,要保证其唯一性
          uri: lb://user-service # lb 表示 从nacos 中按照名称获取微服务，并遵循负载均衡策略, user-service 即微服务注册名
          predicates:
            - Path=/users/**  # 使用断言
#          filters:
#            - AuthFilter